name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: '3 3 * * 2' # 3:03 AM, every Tuesday

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-podspecs:
    name: lint podspecs
    runs-on: macos-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required to be able to find Git tags

      - name: Lint Introspect.podspec
        run: |
          set -eo pipefail
          export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod lib lint Introspect.podspec --allow-warnings

      - name: Lint SwiftUIIntrospect.podspec
        run: |
          set -eo pipefail
          export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod lib lint SwiftUIIntrospect.podspec --allow-warnings

  ci:
    name: ${{ matrix.platform[0] }} ${{ matrix.platform[1] }}
    runs-on: ${{ matrix.os || 'macos-13' }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - [visionos, 1]
        include:
          - platform: [visionos, 1]
            runtime: visionOS 1.0-beta2
            os: macos-13
            install: true
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup tea environment
        uses: teaxyz/setup@v0
        with:
          +: |
            github.com/XcodesOrg/xcodes

      - name: Select Xcode version
        run: sudo xcodes select ${{ matrix.xcode || '15.0' }}

      - if: ${{ matrix.install }}
        name: Install Required Runtime (${{ matrix.runtime }})
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: sudo xcodes runtimes install '${{ matrix.runtime }}'

      - name: List Available Runtimes and Simulators
        run: xcrun simctl list

      - if: ${{ join(matrix.platform, ' ') != 'macos 11' }}
        name: Build Showcase
        run: fastlane build platform:${{ matrix.platform[0] }} version:${{ matrix.platform[1] }} scheme:Showcase

      - if: ${{ join(matrix.platform, ' ') != 'ios 13' && join(matrix.platform, ' ') != 'tvos 13' && join(matrix.platform, ' ') != 'ios 17' && join(matrix.platform, ' ') != 'tvos 17' && matrix.platform[0] != 'visionos' }}
        name: Run Tests (Introspect)
        run: fastlane test platform:${{ matrix.platform[0] }} version:${{ matrix.platform[1] }} scheme:Introspect

      - if: ${{ join(matrix.platform, ' ') != 'macos 11' }}
        name: Run Tests (SwiftUIIntrospect)
        run: fastlane test platform:${{ matrix.platform[0] }} version:${{ matrix.platform[1] }} scheme:SwiftUIIntrospectTests configuration:Debug

      - if: ${{ matrix.platform[0] == 'ios' && matrix.platform[1] >= '14' && matrix.platform[1] <= '16' }}
        name: Run UI Tests (SwiftUIIntrospect)
        run: fastlane test platform:${{ matrix.platform[0] }} version:${{ matrix.platform[1] }} scheme:SwiftUIIntrospectUITests configuration:Debug
